name: Test on Merge to Main

on:
  push:
    branches:
      - jdbc

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mn_playground
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.8'

      - name: Build with Gradle
        run: gradle build

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-jar
          path: build/libs/*.jar
